import { pgTable, text, timestamp, boolean, jsonb } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), role: text('role').notNull().default('patient') })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }) })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow(), updatedAt: timestamp('updatedAt').defaultNow() })
export const healthProfiles = pgTable('health_profiles', { userId: text('userId').primaryKey(), data: jsonb('data').notNull(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const healthRecords = pgTable('health_records', { id: text('id').primaryKey(), userId: text('userId').notNull(), data: jsonb('data').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const consents = pgTable('consents', { id: text('id').primaryKey(), userId: text('userId').notNull(), data: jsonb('data').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const auditEvents = pgTable('audit_events', { id: text('id').primaryKey(), userId: text('userId').notNull(), data: jsonb('data').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const notifications = pgTable('notifications', { id: text('id').primaryKey(), userId: text('userId').notNull(), data: jsonb('data').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const emergencyTokens = pgTable('emergency_tokens', { id: text('id').primaryKey(), userId: text('userId').notNull(), tokenHash: text('token_hash').notNull().unique(), enabled: boolean('enabled').notNull().default(true), sharedItems: jsonb('sharedItems').notNull().default([]), createdAt: timestamp('createdAt').notNull().defaultNow(), revokedAt: timestamp('revokedAt') })
