"use client"

import { useState } from "react"
import Link from "next/link"
import { ArrowRight, Check, HeartPulse, ShieldCheck } from "lucide-react"

export default function AuthForm({ signup = false }: { signup?: boolean }) {
  const [values, setValues] = useState({ name: "", email: "", mobile: "", dob: "", password: "", confirm: "" })
  const [error, setError] = useState("")
  const [loading, setLoading] = useState(false)
  const submit = (e: React.FormEvent) => { e.preventDefault(); setError(""); if (!values.email || !values.password || (signup && (!values.name || values.password !== values.confirm))) { setError(signup ? "Complete all fields and make sure passwords match." : "Enter your email and password."); return } setLoading(true); setTimeout(() => { localStorage.setItem("resq-session", JSON.stringify({ authenticated: true, role: "patient" })); if (signup) localStorage.setItem("resq-profile", JSON.stringify({ name: values.name, dob: values.dob, blood: "O+", contact: values.mobile, allergies: "Penicillin", medication: "Insulin · 10 units · Twice daily", conditions: "Diabetes", procedures: "Appendectomy · 2024" })); window.location.href = "/dashboard" }, 700) }
  const field = (label: string, key: keyof typeof values, type = "text", required = true) => <label>{label}<input required={required} type={type} value={values[key]} onChange={e => setValues({...values, [key]: e.target.value})}/></label>
  return <main className="auth-page"><div className="auth-brand"><Link href="/"><span className="logo-mark"><HeartPulse size={19}/></span> RESQ<span>NOW</span></Link><span className="demo-chip"><span className="status-dot"/> Demo authentication</span></div><section className="auth-card card"><div className="auth-heading"><span className="eyebrow">{signup ? "CREATE YOUR WALLET" : "WELCOME BACK"}</span><h1>{signup ? "Your health wallet starts here." : "Log in to RESQNOW."}</h1><p>{signup ? "Create a patient-controlled home for your verified health information." : "Access your verified health profile and consent controls."}</p></div><form onSubmit={submit}>{signup && <div className="auth-grid">{field("Full name", "name")}{field("Mobile number", "mobile")}{field("Date of birth", "dob", "date")}</div>}{field("Email or mobile number", "email", "email")}{field("Password", "password", "password")}{signup && field("Confirm password", "confirm", "password")} {signup && <label className="check-row"><input type="checkbox" required/> I agree to use this demo wallet and understand it contains fictional data.</label>}{error && <p className="form-error" role="alert">{error}</p>}<button className="btn primary auth-submit" disabled={loading}>{loading ? "Creating your health wallet..." : signup ? "Create account" : "Log in"}<ArrowRight size={16}/></button></form><div className="auth-foot">{signup ? <>Already have a wallet? <Link href="/login">Log in</Link></> : <>New to RESQNOW? <Link href="/signup">Create an account</Link></>}</div><div className="auth-trust"><ShieldCheck size={15}/> Consent-controlled · Demo data only</div></section></main>
}
