import type { AuditEvent, AppSettings, Consent, EmergencyQR, MedicalRecord, Notification, PatientProfile, Provider } from "./types"

export const mockProfile: PatientProfile = { id: "patient-demo", name: "Sandhiya Prakash", dob: "1998-09-18", bloodGroup: "O+", emergencyContact: "+91 XXXXX XXXXX", allergies: ["Penicillin"], medications: ["Insulin · 10 units · Twice daily"], conditions: ["Diabetes"], procedures: ["Appendectomy · 2024"] }
export const mockProviders: Provider[] = [{ id: "dr-priya", name: "Dr. Priya Shah", facility: "City Hospital", role: "Consulting physician" }, { id: "dr-kumar", name: "Dr. Kumar", facility: "City Hospital", role: "Emergency physician" }, { id: "apollo", name: "Apollo Diagnostics", facility: "Apollo Diagnostics", role: "Laboratory" }]
export const mockRecords: MedicalRecord[] = ["Blood Test|Apollo Diagnostics|12 Aug 2026|Lab Reports", "Prescription|Dr. Priya Shah|08 Aug 2026|Prescriptions", "Discharge Summary|City Hospital|20 Jul 2026|Discharge Summaries", "Scan Report|Apollo Diagnostics|04 Jul 2026|Lab Reports"].map((item, index) => { const [title, provider, date, type] = item.split("|"); return { id: ["blood-test", "prescription", "discharge", "scan-report"][index], title, provider, facility: provider, date, type, status: "VERIFIED" } })
export const mockConsents: Consent[] = [{ id: "consent-priya", providerId: "dr-priya", providerName: "Dr. Priya Shah", facility: "City Hospital", selectedData: ["Allergies", "Medications", "Recent Lab Reports"], purpose: "Consultation", createdAt: "2026-08-14T10:30:00Z", expiresAt: "2026-08-24T10:30:00Z", status: "ACTIVE" }]
export const mockAudit: AuditEvent[] = [{ id: "audit-1", actor: "Dr. Priya Shah", action: "Viewed Allergies", time: "Today · 10:32 AM", status: "AUTHORIZED" }, { id: "audit-2", actor: "City Hospital", action: "Viewed Lab Reports", time: "Today · 09:15 AM", status: "AUTHORIZED" }, { id: "audit-3", actor: "Dr. Kumar", action: "Prescription access expired", time: "Yesterday", status: "EXPIRED" }]
export const mockNotifications: Notification[] = [{ id: "notice-1", title: "New access activity", body: "Dr. Priya Shah viewed your allergies.", read: false, createdAt: "Today · 10:32 AM" }]
export const mockEmergencyQR: EmergencyQR = { id: "qr-demo-1", status: "ACTIVE", updatedAt: "Today · 10:32 AM", sharedItems: ["Blood group", "Allergies", "Medication", "Condition"] }
export const mockSettings: AppSettings = { demoMode: true, notificationsEnabled: true, emergencyProfileEnabled: true }
