import type { N8nWorkflow } from "./types"

/**
 * Catalog of the automation workflows shipped in /workflows (importable files).
 * The Automations screen renders this list; the files map 1:1 to what you
 * import into the automation engine.
 */
export const N8N_WORKFLOWS: N8nWorkflow[] = [
  {
    id: "wf-emergency",
    name: "Emergency QR responder packet",
    trigger: "Webhook — emergency.access",
    description: "Fires when the emergency QR is scanned or the responder view is opened. Builds a read-only critical-info packet (blood group, allergies, medications, conditions, contact), writes an audit event, and alerts the patient's emergency contact.",
    file: "workflows/1-emergency-responder-packet.json",
    wiredTo: ["/emergency-access (QR scan)", "Workflows page test button"],
    active: true,
    demoRuns: [],
  },
  {
    id: "wf-consent",
    name: "Consent lifecycle automation",
    trigger: "Webhook — consent.granted / consent.revoked",
    description: "On grant: validates expiry window, notifies the provider, schedules expiry. On revoke: cuts access immediately, logs the revocation, and unshares the affected data scopes.",
    file: "workflows/2-consent-lifecycle.json",
    wiredTo: ["Consent & sharing page"],
    active: true,
    demoRuns: [],
  },
  {
    id: "wf-record",
    name: "Record intake & verification",
    trigger: "Webhook — record.added",
    description: "Receives a newly uploaded record, checks the provider signature and metadata completeness, flags it PENDING/VERIFIED, and creates a notification when verification completes.",
    file: "workflows/3-record-intake.json",
    wiredTo: ["Medical records page"],
    active: true,
    demoRuns: [],
  },
  {
    id: "wf-audit",
    name: "Audit trail writer",
    trigger: "Webhook — audit.event",
    description: "Single sink for every access event: appends a tamper-evident audit entry, rolls up daily summaries, and escalates unusual access patterns to the notification fan-out workflow.",
    file: "workflows/4-audit-trail.json",
    wiredTo: ["All patient actions", "Access history page"],
    active: true,
    demoRuns: [],
  },
  {
    id: "wf-notify",
    name: "Access notification fan-out",
    trigger: "Webhook — notify.access",
    description: "Fan-out notifications when someone accesses shared data: in-app alert, optional email/SMS nodes (disabled until credentials are attached), and digest batching.",
    file: "workflows/5-notification-fanout.json",
    wiredTo: ["Consent & sharing page", "Records detail page"],
    active: true,
    demoRuns: [],
  },
  {
    id: "wf-auth",
    name: "Patient onboarding flow",
    trigger: "Webhook — auth.signed_up",
    description: "Welcomes new wallets, provisions the default emergency QR and starter records, and seeds the first consent for the patient's primary provider.",
    file: "workflows/6-patient-onboarding.json",
    wiredTo: ["Sign-up page"],
    active: true,
    demoRuns: [],
  },
  {
    id: "wf-emergency-coordination",
    name: "Emergency coordination",
    trigger: "Webhook — emergency.started / hospital.accepted / ambulance.assigned",
    description: "Coordinates the full emergency: case creation, triage acknowledgement, hospital pre-alert with trauma-team preparation, and ambulance ETA synchronization.",
    file: "workflows/7-emergency-coordination.json",
    wiredTo: ["Emergency Center"],
    active: true,
    demoRuns: [],
  },
  {
    id: "wf-ocr",
    name: "Document OCR & verification",
    trigger: "Webhook — document.uploaded / document.extracted",
    description: "Receives uploads, queues OCR + AI structuring, returns per-field confidence. AI output is never auto-verified — a provider verifies against the original.",
    file: "workflows/8-document-ocr.json",
    wiredTo: ["Documents page", "/api/documents/extract"],
    active: true,
    demoRuns: [],
  },
  {
    id: "wf-access",
    name: "Consent & access requests",
    trigger: "Webhook — access.requested / approved / denied / consent.revoked",
    description: "Provider access requests notify the patient wallet (ALLOW/DENY); approvals issue scoped, time-limited grants; denials and revocations cut access immediately.",
    file: "workflows/9-access-requests.json",
    wiredTo: ["Requests page", "Doctor portal"],
    active: true,
    demoRuns: [],
  },
  {
    id: "wf-notify-router",
    name: "Notification router",
    trigger: "Webhook — notify.* (audience: patient / provider / hospital)",
    description: "One central router: determines recipient and channel for every event — wallet inbox, provider email, hospital desk.",
    file: "workflows/10-notification-router.json",
    wiredTo: ["/api/notifications", "Requests page"],
    active: true,
    demoRuns: [],
  },
  {
    id: "wf-qr",
    name: "Emergency QR security",
    trigger: "Webhook — qr.scanned / qr.revoked / qr.generated",
    description: "Audits every QR scan (who, when, purpose, data accessed), enforces rate limits, and rotates tokens so old QR codes stop working instantly.",
    file: "workflows/11-qr-security.json",
    wiredTo: ["Emergency QR page", "/api/qr/[token]"],
    active: true,
    demoRuns: [],
  },
]
